"use client";

import { FormEvent, useEffect, useState } from "react";
import { AuthLoading, useRequireAuth } from "@/components/route-guards";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { FinancialShell, useSelectedHousehold } from "@/components/financial/financial-shell";
import { FinancialError } from "@/components/financial/financial-error";
import { archiveCategory, createCategory, listCategories, type Category } from "@/lib/api-client";

export default function CategoriesPage() {
  const auth = useRequireAuth(); const { selected } = useSelectedHousehold(); const [categories, setCategories] = useState<Category[]>([]); const [name, setName] = useState(""); const [kind, setKind] = useState<"income" | "expense">("expense"); const [visibility, setVisibility] = useState<"shared" | "private">("shared"); const [error, setError] = useState(""); const [archiveTarget, setArchiveTarget] = useState<Category | null>(null); const [archiving, setArchiving] = useState(false);
  const refresh = () => { if (selected) listCategories(selected.id).then((response) => setCategories(response?.categories ?? [])).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Categories could not be loaded.")); };
  useEffect(refresh, [selected]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!selected || !name.trim()) return; try { await createCategory(selected.id, { name: name.trim(), kind, visibility }); setName(""); refresh(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Category could not be created."); } }
  async function archive() { if (!selected || !archiveTarget) return; setArchiving(true); try { await archiveCategory(selected.id, archiveTarget.id); setArchiveTarget(null); refresh(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Category could not be archived."); } finally { setArchiving(false); } }
  if (auth.status === "loading" || auth.status === "unauthenticated") return <AuthLoading />;
  const renderGroup = (group: "income" | "expense") => <div className="mt-3 flex flex-wrap gap-2">{categories.filter((category) => category.kind === group).map((category) => <div key={category.id} className={`flex items-center gap-2 rounded-full px-3 py-2 text-sm ${category.archived_at ? "bg-[#eee7da] text-[#789089]" : "bg-[#edf4ef]"}`}><span>{category.name}{category.is_default ? " · default" : ""}{category.archived_at ? " · archived" : ""}</span>{!category.archived_at && !category.is_default && <button type="button" onClick={() => setArchiveTarget(category)} aria-label={`Archive ${category.name}`} className="font-bold text-[#8c3028]">×</button>}</div>)}</div>;
  return <FinancialShell title="Categories"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="rounded-2xl border border-[#d9cdb9] bg-[#fffdf8] p-5">{error && <FinancialError message={error} />}<h2 className="font-semibold">Income</h2>{renderGroup("income")}<h2 className="mt-8 font-semibold">Expenses</h2>{renderGroup("expense")}</div><form onSubmit={submit} className="h-fit rounded-2xl border border-[#d9cdb9] bg-[#fffdf8] p-5"><h2 className="font-semibold">Add custom category</h2><label htmlFor="category-name" className="mt-4 block text-sm font-semibold">Name<input id="category-name" value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-xl border border-[#cdbfa9] bg-[#fffdf8] px-3 py-3 focus:outline-none" /></label><label htmlFor="category-kind" className="mt-4 block text-sm font-semibold">Kind<select id="category-kind" value={kind} onChange={(event) => setKind(event.target.value as "income" | "expense")} className="mt-2 w-full rounded-xl border border-[#cdbfa9] bg-[#fffdf8] px-3 py-3"><option value="income">Income</option><option value="expense">Expense</option></select></label><label htmlFor="category-visibility" className="mt-4 block text-sm font-semibold">Visibility<select id="category-visibility" value={visibility} onChange={(event) => setVisibility(event.target.value as "shared" | "private")} className="mt-2 w-full rounded-xl border border-[#cdbfa9] bg-[#fffdf8] px-3 py-3"><option value="shared">Shared</option><option value="private">Private</option></select></label><button className="mt-5 rounded-xl bg-[#0f4c4c] px-4 py-3 font-semibold text-white">Create category</button></form></div>{archiveTarget && <ConfirmDialog title={`Archive ${archiveTarget.name}?`} description="Historical transactions keep this category, but new transactions will no longer be able to select it." confirmLabel="Archive category" onConfirm={archive} onCancel={() => setArchiveTarget(null)} busy={archiving} />}</FinancialShell>;
}
