"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AuthLoading, useRequireAuth } from "@/components/route-guards";
import { FinancialShell, useSelectedHousehold } from "@/components/financial/financial-shell";
import { FinancialError } from "@/components/financial/financial-error";
import { FormField } from "@/components/form-field";
import { createTransaction, listAccounts, listCategories, type Account, type Category } from "@/lib/api-client";
import { positiveAmountToImpact, todayInTimeZone } from "@/lib/financial-format";
import { availableCategories } from "@/lib/financial-rules";

export default function NewTransactionPage() {
  const auth = useRequireAuth(); const { selected } = useSelectedHousehold(); const router = useRouter();
  const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [kind, setKind] = useState<"income" | "expense">("expense"); const [accountId, setAccountId] = useState(""); const [categoryId, setCategoryId] = useState(""); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [notes, setNotes] = useState(""); const [occurredOn, setOccurredOn] = useState(""); const [status, setStatus] = useState<"pending" | "posted">("posted"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!selected) return; Promise.all([listAccounts(selected.id), listCategories(selected.id)]).then(([accountsResponse, categoriesResponse]) => { setAccounts((accountsResponse?.accounts ?? []).filter((account) => !account.archived_at)); setCategories(categoriesResponse?.categories ?? []); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Form data could not be loaded.")); }, [selected]);
  const availableTransactionCategories = availableCategories(categories, kind, accounts.find((account) => account.id === Number(accountId)));
  const effectiveOccurredOn = occurredOn || (selected ? todayInTimeZone(selected.time_zone) : "");
  async function submit(event: FormEvent) { event.preventDefault(); if (!selected || !accountId || !categoryId || !amount || !description.trim()) return setError("Complete all required fields."); setSaving(true); setError(""); try { await createTransaction(selected.id, { account_id: Number(accountId), category_id: Number(categoryId), kind, account_impact: positiveAmountToImpact(kind, amount), status, occurred_on: effectiveOccurredOn, description: description.trim(), notes }, crypto.randomUUID()); router.push("/app"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Transaction could not be saved."); } finally { setSaving(false); } }
  if (auth.status === "loading" || auth.status === "unauthenticated") return <AuthLoading />;
  return <FinancialShell title="Record income or expense"><form onSubmit={submit} className="max-w-2xl space-y-5 rounded-2xl border border-[#d9cdb9] bg-[#fffdf8] p-6"><FinancialError message={error} /><div className="flex gap-2"><button type="button" onClick={() => setKind("income")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${kind === "income" ? "bg-[#0f4c4c] text-white" : "border border-[#cdbfa9]"}`}>Income</button><button type="button" onClick={() => setKind("expense")} className={`rounded-xl px-4 py-2 text-sm font-semibold ${kind === "expense" ? "bg-[#0f4c4c] text-white" : "border border-[#cdbfa9]"}`}>Expense</button></div><div><label htmlFor="transaction-account" className="block text-sm font-semibold">Account</label><select id="transaction-account" value={accountId} onChange={(event) => setAccountId(event.target.value)} className="mt-2 w-full rounded-xl border border-[#cdbfa9] bg-[#fffdf8] px-4 py-3"><option value="">Select an account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></div><div><label htmlFor="transaction-category" className="block text-sm font-semibold">Category</label><select id="transaction-category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="mt-2 w-full rounded-xl border border-[#cdbfa9] bg-[#fffdf8] px-4 py-3"><option value="">Select a category</option>{availableTransactionCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><FormField id="transaction-amount" label="Amount" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.0000" /><FormField id="transaction-description" label="Description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What was this for?" /><FormField id="transaction-notes" label="Notes (optional)" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional context" /><FormField id="transaction-date" label="Date" type="date" value={effectiveOccurredOn} onChange={(event) => setOccurredOn(event.target.value)} /><div><label htmlFor="transaction-status" className="block text-sm font-semibold">Status</label><select id="transaction-status" value={status} onChange={(event) => setStatus(event.target.value as "pending" | "posted")} className="mt-2 w-full rounded-xl border border-[#cdbfa9] bg-[#fffdf8] px-4 py-3"><option value="posted">Posted</option><option value="pending">Pending</option></select></div><button disabled={saving} className="rounded-xl bg-[#0f4c4c] px-5 py-3 font-semibold text-white disabled:opacity-60">{saving ? "Saving…" : "Save transaction"}</button></form></FinancialShell>;
}
